{
  description = "Slopium language toolchain: slopic compiler and slopium project manager";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      supportedSystems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

      # The workspace manifest is the single source of the version. Repeating
      # it here is how the Nix package and `slopium --version` drift apart.
      version =
        (builtins.fromTOML (builtins.readFile ./Cargo.toml)).workspace.package.version;

      source = nixpkgs.lib.cleanSourceWith {
        src = ./.;
        filter = path: type:
          let name = baseNameOf path;
          in name != ".git" && name != ".notes" && name != "target"
             && name != "changelog.d";
      };

      # Both the overlay and the per-system outputs build from these two
      # functions, so an importer of the overlay gets exactly the package
      # `nix build` produces.
      mkToolchain = pkgs: pkgs.rustPlatform.buildRustPackage {
        pname = "slopium";
        inherit version;
        src = source;

        cargoLock.lockFile = ./Cargo.lock;
        nativeBuildInputs = [
          pkgs.makeWrapper
          pkgs.installShellFiles
          pkgs.stdenv.cc
          # The git-dependency tests build a repository in a temporary
          # directory and fetch from it, which needs `git` in the sandbox —
          # and nothing else, because nothing there reaches the network.
          pkgs.git
          # The registry transport test serves a directory over loopback and
          # fetches it back. Same rule: the only host it talks to is itself.
          pkgs.curl
        ];

        cargoBuildFlags = [ "--workspace" ];
        cargoTestFlags = [ "--workspace" ];

        installPhase = ''
          runHook preInstall
          mkdir -p "$out/bin"
          cp \
            target/${pkgs.stdenv.hostPlatform.rust.rustcTarget}/release/slopic \
            target/${pkgs.stdenv.hostPlatform.rust.rustcTarget}/release/slopium \
            target/${pkgs.stdenv.hostPlatform.rust.rustcTarget}/release/slopium-lsp \
            "$out/bin/"
          runHook postInstall
        '';

        # Completions are generated by the binaries themselves, before the
        # wrappers rename them, so the scripts can never describe a CLI the
        # build does not have.
        postInstall = ''
          for shell in bash zsh fish; do
            "$out/bin/slopium" completions "$shell" > "slopium.$shell"
            "$out/bin/slopic" --completions "$shell" > "slopic.$shell"
          done
          installShellCompletion --cmd slopium \
            --bash slopium.bash --zsh slopium.zsh --fish slopium.fish
          installShellCompletion --cmd slopic \
            --bash slopic.bash --zsh slopic.zsh --fish slopic.fish

          wrapProgram "$out/bin/slopic" \
            --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.stdenv.cc ]}
          wrapProgram "$out/bin/slopium" \
            --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.stdenv.cc ]}
        '';

        meta = {
          description = "Native S-expression compiler and project manager";
          license = pkgs.lib.licenses.mit;
          platforms = supportedSystems;
          mainProgram = "slopium";
        };
      };

      # Build a Slopium package from its own `Slopium.lock` (`D-061`).
      #
      # Nix does no version selection. The lock is the plan: every registry
      # entry becomes a fixed-output derivation keyed by the checksum the lock
      # already records, those fill a package store, and the build runs
      # `--offline --locked`. That is what makes "Cargo and Nix resolve
      # identical locked graphs" true by construction — there is one resolver,
      # it ran once, and both builds read what it wrote.
      #
      # `registries` maps the index string a lock records to the directory it
      # is, because a relative path in a lockfile means nothing to Nix.
      mkLib = pkgs:
        let
          toolchain = mkToolchain pkgs;
          inherit (pkgs) lib;
        in
        {
          buildSlopiumPackage =
            { pname
            , version
            , src
            , registries ? { }
            , profile ? "release"
            , ...
            }@arguments:
            let
              lock = builtins.fromTOML (builtins.readFile "${src}/Slopium.lock");

              # A path package is already inside `src`, and the bundled library
              # is inside the compiler. Neither is anything to fetch, which is
              # the same rule resolution itself follows. The library does carry
              # a checksum — that is how a lock notices a toolchain whose
              # library changed — so it is excluded by its source, not by the
              # absence of one.
              fetched = builtins.filter
                (package: package ? checksum && package.source != "toolchain")
                lock.package;

              archiveOf = package:
                let
                  index = lib.removePrefix "registry+" package.source;
                  base = registries.${index} or (throw ''
                    `${pname}` locks `${package.name}` to the registry `${index}`,
                    which is not in `registries`. Pass `registries."${index}" = <path>;`
                    so the bridge knows where that index is on this machine.
                  '');
                  file = "packages/${package.name}/${package.name}-${package.version}.sl.tar";
                in
                if lib.hasPrefix "registry+" package.source then {
                  inherit (package) name checksum;
                  # A genuine fixed-output derivation, and its hash is the
                  # lock's own checksum rather than one kept in step by hand.
                  archive = pkgs.fetchurl {
                    name = "${package.name}-${package.version}.sl.tar";
                    url = "file://${base}/${file}";
                    sha256 = package.checksum;
                  };
                  # The signature is read straight out of the registry
                  # directory: it has no hash in the lock, so there is nothing
                  # to key a fixed-output derivation on. A registry reachable
                  # only over `https://` therefore arrives unsigned here, and a
                  # build that requires signatures needs a local copy of it.
                  signature = "${base}/${file}.sig";
                }
                else throw ''
                  SL1044: `${pname}` locks `${package.name}` to `${package.source}`,
                  which this bridge cannot fetch. A git package's checksum is the digest
                  of an archive the toolchain normalizes out of an exported tree, so no
                  fixed-output derivation can reproduce it. Run `slopium vendor` and build
                  the vendored graph instead.
                '';

              archives = map archiveOf fetched;

              fill = builtins.concatStringsSep "\n" (map
                (entry: ''
                  cp "${entry.archive}" "$SLOPIUM_HOME/archives/${entry.checksum}.sl.tar"
                  if [ -f "${entry.signature}" ]; then
                    cp "${entry.signature}" "$SLOPIUM_HOME/archives/${entry.checksum}.sl.tar.sig"
                  fi
                '')
                archives);

              triple = pkgs.stdenv.hostPlatform.rust.rustcTarget;
            in
            pkgs.stdenv.mkDerivation (builtins.removeAttrs arguments [ "registries" "profile" ] // {
              inherit pname version src;

              nativeBuildInputs = (arguments.nativeBuildInputs or [ ])
                ++ [ toolchain pkgs.stdenv.cc ];

              configurePhase = ''
                runHook preConfigure
                export SLOPIUM_HOME="$NIX_BUILD_TOP/slopium-home"
                export SLOPIC="${toolchain}/bin/slopic"
                mkdir -p "$SLOPIUM_HOME/archives"
                chmod -R u+w "$SLOPIUM_HOME"
                ${fill}
                chmod -R u+w "$SLOPIUM_HOME"
                runHook postConfigure
              '';

              buildPhase = arguments.buildPhase or ''
                runHook preBuild
                slopium build --offline --locked ${lib.optionalString (profile == "release") "--release"}
                runHook postBuild
              '';

              installPhase = arguments.installPhase or ''
                runHook preInstall
                mkdir -p "$out/bin"
                cp "target/${triple}/${profile}/${pname}" "$out/bin/"
                runHook postInstall
              '';
            });
        };

      mkNeovimPlugin = pkgs: pkgs.vimUtils.buildVimPlugin {
        pname = "slopium.nvim";
        inherit version;
        src = ./editors/nvim;
        meta = {
          description = "Neovim support for the Slopium language";
          license = pkgs.lib.licenses.mit;
        };
      };
    in
    {
      # `nixpkgs.overlays = [ inputs.slopium.overlays.default ]` gives modules
      # `pkgs.slopium` and `pkgs.vimPlugins.slopium-nvim`.
      overlays.default = final: prev: {
        slopium = mkToolchain final;
        vimPlugins = prev.vimPlugins // {
          slopium-nvim = mkNeovimPlugin final;
        };
      };

      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          toolchain = mkToolchain pkgs;
        in
        {
          default = toolchain;
          slopium = toolchain;
          slopium-nvim = mkNeovimPlugin pkgs;
        });

      # System-wide toolchain. Editor support is a user-level concern and
      # lives in `homeModules.default`.
      nixosModules.default = { config, lib, pkgs, ... }:
        let cfg = config.programs.slopium;
        in
        {
          options.programs.slopium = {
            enable = lib.mkEnableOption "the Slopium toolchain";

            package = lib.mkOption {
              type = lib.types.package;
              default = self.packages.${pkgs.stdenv.hostPlatform.system}.slopium;
              defaultText = lib.literalExpression "slopium.packages.\${system}.slopium";
              description = "Package providing slopic, slopium, and slopium-lsp.";
            };

            overlay = lib.mkOption {
              type = lib.types.bool;
              default = true;
              description = ''
                Add the Slopium overlay to nixpkgs, so other modules can refer
                to `pkgs.slopium` and `pkgs.vimPlugins.slopium-nvim`.
              '';
            };
          };

          config = lib.mkIf cfg.enable {
            nixpkgs.overlays = lib.mkIf cfg.overlay [ self.overlays.default ];
            environment.systemPackages = [ cfg.package ];
          };
        };

      # User-level: the toolchain in the profile and the Neovim plugin, which
      # `scripts/install-nvim.sh` otherwise symlinks by hand.
      homeModules.default = { config, lib, pkgs, ... }:
        let cfg = config.programs.slopium;
        in
        {
          options.programs.slopium = {
            enable = lib.mkEnableOption "the Slopium toolchain in the user profile";

            package = lib.mkOption {
              type = lib.types.package;
              default = self.packages.${pkgs.stdenv.hostPlatform.system}.slopium;
              defaultText = lib.literalExpression "slopium.packages.\${system}.slopium";
              description = "Package providing slopic, slopium, and slopium-lsp.";
            };

            neovim = {
              enable = lib.mkEnableOption "the slopium.nvim plugin";

              package = lib.mkOption {
                type = lib.types.package;
                default = self.packages.${pkgs.stdenv.hostPlatform.system}.slopium-nvim;
                defaultText = lib.literalExpression "slopium.packages.\${system}.slopium-nvim";
                description = "The Neovim plugin to install as a native package.";
              };

              lazySpec = lib.mkOption {
                type = lib.types.bool;
                default = false;
                description = ''
                  Also write `~/.config/nvim/lua/plugins/slopium.lua`. Needed by
                  configurations whose plugin manager resets `runtimepath` and
                  therefore never sees native packages — lazy.nvim does this by
                  default.
                '';
              };
            };
          };

          config = lib.mkMerge [
            (lib.mkIf cfg.enable {
              home.packages = [ cfg.package ];
            })
            (lib.mkIf cfg.neovim.enable {
              home.file.".local/share/nvim/site/pack/slopium/start/slopium.nvim".source =
                cfg.neovim.package;

              # `lazy-spec.lua` derives the plugin directory from its own
              # resolved path, so a symlink into the store points lazy.nvim at
              # the store copy and nothing has to be templated here.
              xdg.configFile."nvim/lua/plugins/slopium.lua" = lib.mkIf cfg.neovim.lazySpec {
                source = "${cfg.neovim.package}/lazy-spec.lua";
              };
            })
          ];
        };

      apps = forAllSystems (system:
        let
          package = self.packages.${system}.default;
        in
        {
          default = {
            type = "app";
            program = "${package}/bin/slopium";
            meta.description = "Run the Slopium project manager";
          };
          slopium = {
            type = "app";
            program = "${package}/bin/slopium";
            meta.description = "Run the Slopium project manager";
          };
          slopic = {
            type = "app";
            program = "${package}/bin/slopic";
            meta.description = "Run the low-level Slopium compiler";
          };
          slopium-lsp = {
            type = "app";
            program = "${package}/bin/slopium-lsp";
            meta.description = "Run the Slopium language server";
          };
        });

      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          # The cross toolchain and the emulator are what make the second
          # backend testable: `slopic` needs an aarch64 `cc` to assemble and
          # link what it emits, and `qemu-aarch64` is how the result is run on
          # an x86-64 host. Neither is needed to build the compiler itself, so
          # they are in the dev shell only.
          #
          # The same `qemu` carries `qemu-system-x86_64`, which is a different
          # claim rather than the same one twice: user-mode emulation runs a
          # program on a kernel that already exists, and `kernel-check.sh` boots
          # one that does not.
          crossCc = pkgs.pkgsCross.aarch64-multiplatform.stdenv.cc;
        in
        {
          default = pkgs.mkShell {
            packages = with pkgs; [
              rustc
              cargo
              rustfmt
              clippy
              stdenv.cc
              binutils
              git
              curl
              gdb
              valgrind
              crossCc
              qemu
            ];

            shellHook = ''
              echo "Slopium development shell"
              echo "  cargo build --workspace"
              echo "  cargo test --workspace"
              export SLOPIUM_CC_AARCH64_UNKNOWN_LINUX_GNU=${crossCc.targetPrefix}cc
              export SLOPIUM_QEMU_AARCH64=qemu-aarch64
              export SLOPIUM_QEMU_SYSTEM_X86_64=qemu-system-x86_64
            '';
          };
        });

      formatter = forAllSystems (system:
        let pkgs = import nixpkgs { inherit system; };
        in pkgs.nixfmt);

      # `nixpkgs.lib` is system-independent; this one is not, because building a
      # package needs a toolchain built for a system.
      lib = forAllSystems (system: mkLib (import nixpkgs { inherit system; }));

      checks = forAllSystems (system:
        let pkgs = import nixpkgs { inherit system; };
        in {
          package = self.packages.${system}.default;
          neovim-plugin = self.packages.${system}.slopium-nvim;

          # The milestone's exit condition, as a build. The consumer's lock, its
          # registry and the signature over the package it names are all
          # committed, so this resolves nothing, fetches every archive as a
          # fixed-output derivation keyed by the lock's checksum, verifies the
          # signature against the key in the consumer's own configuration, and
          # runs what comes out.
          lock-build = (self.lib.${system}.buildSlopiumPackage {
            pname = "consumer";
            version = "0.1.0";
            src = ./tests/consumer;
            registries."../registry" = ./tests/registry;
          }).overrideAttrs (previous: {
            doCheck = true;
            checkPhase = ''
              runHook preCheck
              actual="$(./target/${pkgs.stdenv.hostPlatform.rust.rustcTarget}/release/consumer)"
              if [ "$actual" != "100" ]; then
                echo "the package built from the lock printed '$actual', not 100" >&2
                exit 1
              fi
              runHook postCheck
            '';
          });
        });
    };
}
