{
  description = "Slopium language toolchain: slopic compiler and slopium project manager";

  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs }:
    let
      supportedSystems = [ "x86_64-linux" ];
      forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

      # The workspace manifest is the single source of the version. Repeating
      # it here is how the Nix package and `slopium --version` drift apart.
      version =
        (builtins.fromTOML (builtins.readFile ./Cargo.toml)).workspace.package.version;

      source = nixpkgs.lib.cleanSourceWith {
        src = ./.;
        filter = path: type:
          let name = baseNameOf path;
          in name != ".git" && name != ".notes" && name != "target";
      };

      # Both the overlay and the per-system outputs build from these two
      # functions, so an importer of the overlay gets exactly the package
      # `nix build` produces.
      mkToolchain = pkgs: pkgs.rustPlatform.buildRustPackage {
        pname = "slopium";
        inherit version;
        src = source;

        cargoLock.lockFile = ./Cargo.lock;
        nativeBuildInputs = [
          pkgs.makeWrapper
          pkgs.installShellFiles
          pkgs.stdenv.cc
        ];

        cargoBuildFlags = [ "--workspace" ];
        cargoTestFlags = [ "--workspace" ];

        installPhase = ''
          runHook preInstall
          mkdir -p "$out/bin"
          cp \
            target/${pkgs.stdenv.hostPlatform.rust.rustcTarget}/release/slopic \
            target/${pkgs.stdenv.hostPlatform.rust.rustcTarget}/release/slopium \
            target/${pkgs.stdenv.hostPlatform.rust.rustcTarget}/release/slopium-lsp \
            "$out/bin/"
          runHook postInstall
        '';

        # Completions are generated by the binaries themselves, before the
        # wrappers rename them, so the scripts can never describe a CLI the
        # build does not have.
        postInstall = ''
          for shell in bash zsh fish; do
            "$out/bin/slopium" completions "$shell" > "slopium.$shell"
            "$out/bin/slopic" --completions "$shell" > "slopic.$shell"
          done
          installShellCompletion --cmd slopium \
            --bash slopium.bash --zsh slopium.zsh --fish slopium.fish
          installShellCompletion --cmd slopic \
            --bash slopic.bash --zsh slopic.zsh --fish slopic.fish

          wrapProgram "$out/bin/slopic" \
            --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.stdenv.cc ]}
          wrapProgram "$out/bin/slopium" \
            --prefix PATH : ${pkgs.lib.makeBinPath [ pkgs.stdenv.cc ]}
        '';

        meta = {
          description = "Native S-expression compiler and project manager";
          license = pkgs.lib.licenses.mit;
          platforms = supportedSystems;
          mainProgram = "slopium";
        };
      };

      mkNeovimPlugin = pkgs: pkgs.vimUtils.buildVimPlugin {
        pname = "slopium.nvim";
        inherit version;
        src = ./editors/nvim;
        meta = {
          description = "Neovim support for the Slopium language";
          license = pkgs.lib.licenses.mit;
        };
      };
    in
    {
      # `nixpkgs.overlays = [ inputs.slopium.overlays.default ]` gives modules
      # `pkgs.slopium` and `pkgs.vimPlugins.slopium-nvim`.
      overlays.default = final: prev: {
        slopium = mkToolchain final;
        vimPlugins = prev.vimPlugins // {
          slopium-nvim = mkNeovimPlugin final;
        };
      };

      packages = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          toolchain = mkToolchain pkgs;
        in
        {
          default = toolchain;
          slopium = toolchain;
          slopium-nvim = mkNeovimPlugin pkgs;
        });

      # System-wide toolchain. Editor support is a user-level concern and
      # lives in `homeModules.default`.
      nixosModules.default = { config, lib, pkgs, ... }:
        let cfg = config.programs.slopium;
        in
        {
          options.programs.slopium = {
            enable = lib.mkEnableOption "the Slopium toolchain";

            package = lib.mkOption {
              type = lib.types.package;
              default = self.packages.${pkgs.stdenv.hostPlatform.system}.slopium;
              defaultText = lib.literalExpression "slopium.packages.\${system}.slopium";
              description = "Package providing slopic, slopium, and slopium-lsp.";
            };

            overlay = lib.mkOption {
              type = lib.types.bool;
              default = true;
              description = ''
                Add the Slopium overlay to nixpkgs, so other modules can refer
                to `pkgs.slopium` and `pkgs.vimPlugins.slopium-nvim`.
              '';
            };
          };

          config = lib.mkIf cfg.enable {
            nixpkgs.overlays = lib.mkIf cfg.overlay [ self.overlays.default ];
            environment.systemPackages = [ cfg.package ];
          };
        };

      # User-level: the toolchain in the profile and the Neovim plugin, which
      # `scripts/install-nvim.sh` otherwise symlinks by hand.
      homeModules.default = { config, lib, pkgs, ... }:
        let cfg = config.programs.slopium;
        in
        {
          options.programs.slopium = {
            enable = lib.mkEnableOption "the Slopium toolchain in the user profile";

            package = lib.mkOption {
              type = lib.types.package;
              default = self.packages.${pkgs.stdenv.hostPlatform.system}.slopium;
              defaultText = lib.literalExpression "slopium.packages.\${system}.slopium";
              description = "Package providing slopic, slopium, and slopium-lsp.";
            };

            neovim = {
              enable = lib.mkEnableOption "the slopium.nvim plugin";

              package = lib.mkOption {
                type = lib.types.package;
                default = self.packages.${pkgs.stdenv.hostPlatform.system}.slopium-nvim;
                defaultText = lib.literalExpression "slopium.packages.\${system}.slopium-nvim";
                description = "The Neovim plugin to install as a native package.";
              };

              lazySpec = lib.mkOption {
                type = lib.types.bool;
                default = false;
                description = ''
                  Also write `~/.config/nvim/lua/plugins/slopium.lua`. Needed by
                  configurations whose plugin manager resets `runtimepath` and
                  therefore never sees native packages — lazy.nvim does this by
                  default.
                '';
              };
            };
          };

          config = lib.mkMerge [
            (lib.mkIf cfg.enable {
              home.packages = [ cfg.package ];
            })
            (lib.mkIf cfg.neovim.enable {
              home.file.".local/share/nvim/site/pack/slopium/start/slopium.nvim".source =
                cfg.neovim.package;

              # `lazy-spec.lua` derives the plugin directory from its own
              # resolved path, so a symlink into the store points lazy.nvim at
              # the store copy and nothing has to be templated here.
              xdg.configFile."nvim/lua/plugins/slopium.lua" = lib.mkIf cfg.neovim.lazySpec {
                source = "${cfg.neovim.package}/lazy-spec.lua";
              };
            })
          ];
        };

      apps = forAllSystems (system:
        let
          package = self.packages.${system}.default;
        in
        {
          default = {
            type = "app";
            program = "${package}/bin/slopium";
            meta.description = "Run the Slopium project manager";
          };
          slopium = {
            type = "app";
            program = "${package}/bin/slopium";
            meta.description = "Run the Slopium project manager";
          };
          slopic = {
            type = "app";
            program = "${package}/bin/slopic";
            meta.description = "Run the low-level Slopium compiler";
          };
          slopium-lsp = {
            type = "app";
            program = "${package}/bin/slopium-lsp";
            meta.description = "Run the Slopium language server";
          };
        });

      devShells = forAllSystems (system:
        let
          pkgs = import nixpkgs { inherit system; };
          # The cross toolchain and the emulator are what make the second
          # backend testable: `slopic` needs an aarch64 `cc` to assemble and
          # link what it emits, and `qemu-aarch64` is how the result is run on
          # an x86-64 host. Neither is needed to build the compiler itself, so
          # they are in the dev shell only.
          crossCc = pkgs.pkgsCross.aarch64-multiplatform.stdenv.cc;
        in
        {
          default = pkgs.mkShell {
            packages = with pkgs; [
              rustc
              cargo
              rustfmt
              clippy
              stdenv.cc
              binutils
              gdb
              valgrind
              crossCc
              qemu
            ];

            shellHook = ''
              echo "Slopium development shell"
              echo "  cargo build --workspace"
              echo "  cargo test --workspace"
              export SLOPIUM_CC_AARCH64_UNKNOWN_LINUX_GNU=${crossCc.targetPrefix}cc
              export SLOPIUM_QEMU_AARCH64=qemu-aarch64
            '';
          };
        });

      formatter = forAllSystems (system:
        let pkgs = import nixpkgs { inherit system; };
        in pkgs.nixfmt);

      checks = forAllSystems (system: {
        package = self.packages.${system}.default;
        neovim-plugin = self.packages.${system}.slopium-nvim;
      });
    };
}
